import path from "path";

const REPOSITORIES_DIR = path.resolve(process.cwd(), "repositories");

export function getRepositoryRoot(repositoryId) {
    if (!repositoryId || typeof repositoryId !== "string") {
        throw new Error("repositoryId is required.");
    }

    // UUIDs are generated by the upload route. Restrict the accepted ID
    // format so a user cannot turn this into a filesystem path.
    if (!/^[0-9a-f-]{36}$/i.test(repositoryId)) {
        throw new Error("Invalid repositoryId.");
    }

    return path.join(REPOSITORIES_DIR, repositoryId);
}

export async function assertRepositoryExists(repositoryId, fs) {
    const root = getRepositoryRoot(repositoryId);

    try {
        const stat = await fs.stat(root);
        if (!stat.isDirectory()) {
            throw new Error("Repository is not available.");
        }
    } catch {
        throw new Error("Repository not found.");
    }

    return root;
}
